package com.nemonotfound.nemos.vertical.slabs.datagen;

import com.nemonotfound.nemos.vertical.slabs.reference.VerticalSlabBlockItemIds;
import com.nemonotfound.nemos.vertical.slabs.tags.VerticalSlabBlockTags;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagsProvider;
import net.minecraft.core.HolderLookup;
import net.minecraft.tags.BlockTags;
import org.jetbrains.annotations.NotNull;

import java.util.concurrent.CompletableFuture;

public class BlockTagProvider extends FabricTagsProvider.BlockTagsProvider {

    public BlockTagProvider(FabricPackOutput output, CompletableFuture<HolderLookup.Provider> providerCompletableFuture) {
        super(output, providerCompletableFuture);
    }

    @Override
    protected void addTags(HolderLookup.@NotNull Provider provider) {
        this.tag(BlockTags.MINEABLE_WITH_AXE)
                .addTag(VerticalSlabBlockTags.WOODEN_VERTICAL_SLABS);

        this.tag(BlockTags.MINEABLE_WITH_SHOVEL)
                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_CATTAIL_THATCH_VERTICAL_SLAB.block());

        this.tag(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(VerticalSlabBlockItemIds.STONE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.COBBLESTONE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.MOSSY_COBBLESTONE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.SMOOTH_STONE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.STONE_BRICK_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.MOSSY_STONE_BRICK_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.GRANITE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.POLISHED_GRANITE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.DIORITE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.POLISHED_DIORITE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.ANDESITE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.POLISHED_ANDESITE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.COBBLED_DEEPSLATE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.POLISHED_DEEPSLATE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.DEEPSLATE_BRICK_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.DEEPSLATE_TILE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.TUFF_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.POLISHED_TUFF_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.TUFF_BRICK_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.BRICK_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.MUD_BRICK_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.SANDSTONE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.SMOOTH_SANDSTONE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.CUT_SANDSTONE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.RED_SANDSTONE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.SMOOTH_RED_SANDSTONE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.CUT_RED_SANDSTONE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.PRISMARINE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.PRISMARINE_BRICK_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.DARK_PRISMARINE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.NETHER_BRICK_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.RED_NETHER_BRICK_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.BLACKSTONE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.POLISHED_BLACKSTONE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.POLISHED_BLACKSTONE_BRICK_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.END_STONE_BRICK_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.PURPUR_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.QUARTZ_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.SMOOTH_QUARTZ_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.CUT_COPPER_VERTICAL_SLABS.weathering().unaffected().block())
                .add(VerticalSlabBlockItemIds.CUT_COPPER_VERTICAL_SLABS.weathering().exposed().block())
                .add(VerticalSlabBlockItemIds.CUT_COPPER_VERTICAL_SLABS.weathering().weathered().block())
                .add(VerticalSlabBlockItemIds.CUT_COPPER_VERTICAL_SLABS.weathering().oxidized().block())
                .add(VerticalSlabBlockItemIds.CUT_COPPER_VERTICAL_SLABS.waxed().unaffected().block())
                .add(VerticalSlabBlockItemIds.CUT_COPPER_VERTICAL_SLABS.waxed().exposed().block())
                .add(VerticalSlabBlockItemIds.CUT_COPPER_VERTICAL_SLABS.waxed().weathered().block())
                .add(VerticalSlabBlockItemIds.CUT_COPPER_VERTICAL_SLABS.waxed().oxidized().block());

        this.tag(BlockTags.MINEABLE_WITH_PICKAXE)
                .addOptional(VerticalSlabBlockItemIds.MOSSY_STONE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MOSSY_TUFF_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MOSSY_TUFF_BRICK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MOSSY_BRICK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_STONE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_TUFF_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_TUFF_BRICK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_BRICK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_STONE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_TUFF_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_TUFF_BRICK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_BRICK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_STONE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_TUFF_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_TUFF_BRICK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_BRICK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CUT_WHITE_SANDSTONE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.SMOOTH_WHITE_SANDSTONE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WHITE_SANDSTONE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CUT_ORANGE_SANDSTONE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.SMOOTH_ORANGE_SANDSTONE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.ORANGE_SANDSTONE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CUT_BLACK_SANDSTONE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.SMOOTH_BLACK_SANDSTONE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.BLACK_SANDSTONE_VERTICAL_SLAB.block());
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_BLACK_SANDSTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_SMOOTH_BLACK_SANDSTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_CUT_BLACK_SANDSTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_WHITE_SANDSTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_SMOOTH_WHITE_SANDSTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_CUT_WHITE_SANDSTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_BLUE_SANDSTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_SMOOTH_BLUE_SANDSTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_CUT_BLUE_SANDSTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_PURPLE_SANDSTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_SMOOTH_PURPLE_SANDSTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_CUT_PURPLE_SANDSTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_PINK_SANDSTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_SMOOTH_PINK_SANDSTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_CUT_PINK_SANDSTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_WINDSWEPT_SANDSTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_SMOOTH_WINDSWEPT_SANDSTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_CUT_WINDSWEPT_SANDSTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_DACITE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_DACITE_BRICK_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_CRACKED_DACITE_BRICK_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_MOSSY_DACITE_BRICK_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_CHISELED_DACITE_BRICK_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_DACITE_COBBLESTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_DACITE_TILE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_WHITE_DACITE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_WHITE_DACITE_BRICK_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_CRACKED_WHITE_DACITE_BRICK_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_MOSSY_WHITE_DACITE_BRICK_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_CHISELED_WHITE_DACITE_BRICK_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_WHITE_DACITE_COBBLESTONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_WHITE_DACITE_TILE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_RED_ROCK_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_RED_ROCK_BRICK_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_CRACKED_RED_ROCK_BRICK_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_MOSSY_RED_ROCK_BRICK_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_CHISELED_RED_ROCK_BRICK_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_POLISHED_RED_ROCK_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_RED_ROCK_TILE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_MOSSY_STONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_ROCKY_STONE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_PALE_MUD_BRICK_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_CATTAIL_THATCH_VERTICAL_SLAB.block());

        this.tag(VerticalSlabBlockTags.WOODEN_VERTICAL_SLABS)
                .add(VerticalSlabBlockItemIds.OAK_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.SPRUCE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.BIRCH_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.JUNGLE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.ACACIA_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.DARK_OAK_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.PALE_OAK_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.CRIMSON_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.WARPED_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.MANGROVE_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.BAMBOO_VERTICAL_SLAB.block())
                .add(VerticalSlabBlockItemIds.CHERRY_VERTICAL_SLAB.block())

                .addOptional(VerticalSlabBlockItemIds.MOSSY_OAK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MOSSY_SPRUCE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MOSSY_BIRCH_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MOSSY_JUNGLE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MOSSY_ACACIA_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MOSSY_DARK_OAK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MOSSY_PALE_OAK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MOSSY_CRIMSON_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MOSSY_WARPED_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MOSSY_MANGROVE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MOSSY_BAMBOO_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MOSSY_CHERRY_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_OAK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_SPRUCE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_BIRCH_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_JUNGLE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_ACACIA_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_DARK_OAK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_PALE_OAK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_CRIMSON_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_WARPED_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_MANGROVE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_BAMBOO_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALE_MOSSY_CHERRY_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_OAK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_SPRUCE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_BIRCH_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_JUNGLE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_ACACIA_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_DARK_OAK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_PALE_OAK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_CRIMSON_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_WARPED_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_MANGROVE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_BAMBOO_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.CRIMSON_MOSSY_CHERRY_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_OAK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_SPRUCE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_BIRCH_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_JUNGLE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_ACACIA_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_DARK_OAK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_PALE_OAK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_CRIMSON_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_WARPED_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_MANGROVE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_BAMBOO_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WARPED_MOSSY_CHERRY_VERTICAL_SLAB.block())

                .addOptional(VerticalSlabBlockItemIds.FIR_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PINE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MAPLE_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.REDWOOD_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.MAHOGANY_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.JACARANDA_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.PALM_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.WILLOW_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.DEAD_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.UMBRAN_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.HELLBARK_VERTICAL_SLAB.block())
                .addOptional(VerticalSlabBlockItemIds.EMPYREAL_VERTICAL_SLAB.block());

//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_ASPEN_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_BOABAB_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_BLUE_ENCHANTED_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_CIKA_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_CYPRESS_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_EBONY_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_FIR_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_FLORUS_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_GREEN_ENCHANTED_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_HOLLY_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_IRONWOOD_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_JACARANDA_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_MAHOGANY_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_MAPLE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_PALM_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_PINE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_RAINBOW_EUCALYPTUS_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_REDWOOD_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_SAKURA_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_SKYRIS_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_SPIRIT_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_WHITE_MANGROVE_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_WILLOW_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_WITCH_HAZEL_VERTICAL_SLAB.block())
//                .addOptional(VerticalSlabBlockItemIds.BIOMES_WEVE_GONE_ZELKOVA_VERTICAL_SLAB.block());
    }

}
